services:
  db:
    image: postgres:17-alpine
    container_name: postgres-doPay
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doPay-membership
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:7.2-alpine
    container_name: redis-doPay
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: always
volumes:
  postgres-data:
  redis_data: